### ISSUE TITLE
TLR_PLATFORM_MACOS/IOS not defined

### ISSUE THREAD

**Issue by meshula** [darbyjohnston/tlRender#11]
Where these intended to be set by Cmake? If no, it might be sufficient to replace them with a test against `__APPLE__`.

**Comment by darbyjohnston** [comment]
Oops, look like those are not being set at all. Replacing them with "__APPLE__" sounds like a good change.

**Comment by darbyjohnston** [comment]
I tried removing the conditional and it compiles OK on macOS 10.11.6, so I checked in the change. Apparently stat64 is deprecated since 10.6 so I'm not sure why I had that there.

**Comment by meshula** [comment]
I just did a pull, I'm on 11.3.

```
[ 94%] Performing build step for 'tlRender'
Consolidate compiler generated dependencies of target tlrCore
[  1%] Building CXX object lib/tlrCore/CMakeFiles/tlrCore.dir/FileUnix.cpp.o
/Users/nporcino/dev/tlRender/lib/tlrCore/FileUnix.cpp:28:13: error: no struct named 'stat64' in the global namespace
            _STAT info;
            ^~~~~
/Users/nporcino/dev/tlRender/lib/tlrCore/FileUnix.cpp:18:24: note: expanded from macro '_STAT'
#define _STAT struct ::stat64
                     ~~^
/Users/nporcino/dev/tlRender/lib/tlrCore/FileUnix.cpp:29:37: error: no struct named 'stat64' in the global namespace
            memset(&info, 0, sizeof(_STAT));
                                    ^~~~~
/Users/nporcino/dev/tlRender/lib/tlrCore/FileUnix.cpp:18:24: note: expanded from macro '_STAT'
#define _STAT struct ::stat64
                     ~~^
/Users/nporcino/dev/tlRender/lib/tlrCore/FileUnix.cpp:30:25: error: no member named 'stat64' in the global namespace; did you mean 'stat'?
            return 0 == _STAT_FNC(fileName.c_str(), &info);
                        ^~~~~~~~~
/Users/nporcino/dev/tlRender/lib/tlrCore/FileUnix.cpp:19:24: note: expanded from macro '_STAT_FNC'
#define _STAT_FNC    ::stat64
                     ~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/stat.h:386:9: note: 'stat' declared here
int     stat(const char *, struct stat *) __DARWIN_INODE64(stat);
        ^
3 errors generated.
```

**Comment by meshula** [comment]
just using stat instead of stat64 gets me past the issue...

**Comment by darbyjohnston** [comment]
Hmm, that's odd; I just reverted the change and used the "__APPLE__" macro for the conditional.

**Comment by meshula** [comment]
I'm on 11.3 and M1. Maybe I've hit the trifecta of brokenness. Anyway, `struct stat info;` works; any reason it needs to be stat64? Since all you're testing is existence?

**Comment by darbyjohnston** [comment]
It was an issue on Linux with some file systems but maybe not macOS; I need to read ```man stat64``` a bit more carefully... For now I've checked in a change to use regular ```stat``` on macOS with the ```__APPLE___``` macro like you suggested.

**Comment by darbyjohnston** [comment]
According to the man page, ```stat()```, on macOS uses 64-bit data structures since 10.5 so it looks like the right function to use.
